Repository s-tip/stip-rs, pull requests merged in 2020-09, with the labels that each got.

#81 Fixed to taxii21 mongo settings and some lines by pep8.
  src/ctirs/core/boot_rs.py
  src/ctirs/core/mongo/documents_stix.py
  src/ctirs/models/rs/models.py
Labels: bug

#82 Fixed an issue about installation of RS
  src/ctirs/models/rs/models.py
Labels: bug

#86 Alienvault OTX - Successful Run but no returned stix files #54 and support a popup help window.
  src/ctirs/adapter/isight/templates/isight.html
  src/ctirs/adapter/misp/templates/misp.html
  src/ctirs/adapter/otx/templates/otx.html
  src/ctirs/api/v1/stix_files_v2/views.py
  src/ctirs/core/adapter/__init__.py
  src/ctirs/core/adapter/otx/otx.py
  src/ctirs/poll/templates/poll_detail.html
  src/static/ctirs/js/adapter_isight.js
  src/static/ctirs/js/adapter_misp.js
  src/static/ctirs/js/adapter_otx.js
  src/static/ctirs/js/poll_detail.js
Labels: bug, enhancement

#87 version 1.0.1 -> 1.1
  version
Labels: enhancement

#90 Fixed issues about SECRET_KEYS and TIME_ZONE.
  bin/setup_env.py
  src/ctirs/settings.py
Labels: bug, enhancement

#92 Fixed an issue about migration
  src/ctirs/migrations/0038_auto_20200630_1151.py
  src/ctirs/migrations/0038_auto_20200722_0237.py
Labels: bug
